[project]
name = "case-extreme"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.1",
    "pathlib>=1.0.1",
    "sqlalchemy>=2.0.47",
]
